### ISSUE TITLE
How to build and install the crf_loss?

### ISSUE THREAD

**Issue by Luoxd1996** [huiqu18/WeaklySegPartialPoints#1]
Hi, Dr. Qu,
I want to try your code, but I can not build and install the CRF Loss successfully, my platform is Ubuntu 18.04, PyTorch version is 1.6, and GCC version is 7.5.0. Could you help me, thanks? I am looking forward to your reply.
Best wishes;
Xiangde Luo.

**Comment by huiqu18** [comment]
@Luoxd1996 Can you provide the error reported? I compiled under Ubuntu 16.04, PyTorch 1.0 and GCC 4.9. It could be caused by the Pytorch version since there are a lot of changes in PyTorch 1.6 compared to PyTorch 1.0.

**Comment by Musa-Go** [comment]
@Luoxd1996 I compiled under Ubuntu 18.04, PyTorch 1.0 and GCC 7.5. It could be caused by the PyTorch version.

**Comment by Luoxd1996** [comment]
> @Luoxd1996 Can you provide the error reported? I compiled under Ubuntu 16.04, PyTorch 1.0 and GCC 4.9. It could be caused by the Pytorch version since there are a lot of changes in PyTorch 1.6 compared to PyTorch 1.0.

Thanks for your reply. I wonder that the CUDA and CUDNN are must request to be pre-installed before building and installing the CRF Loss? There are some errors about "ninja" and data type. I will try to use this code in PyTorch 1.0. Anyway, thank you very much.

**Comment by Luoxd1996** [comment]
> @Luoxd1996 I compiled under Ubuntu 18.04, PyTorch 1.0 and GCC 7.5. It could be caused by the PyTorch version.

Thanks for your suggestions, I will test it in PyTorch 1.0.

**Comment by Luoxd1996** [comment]
> @Luoxd1996 Can you provide the error reported? I compiled under Ubuntu 16.04, PyTorch 1.0 and GCC 4.9. It could be caused by the Pytorch version since there are a lot of changes in PyTorch 1.6 compared to PyTorch 1.0.

I tested the code both in Ubuntu18.04 and 20.04, and also in GPU 1080TI and 2080TI, the code can work well when the PyTorch version is 1.0. I wonder that are there some plans to update the code to support  PyTorch 1.6 or 1.7? Thank you very much.

**Comment by huiqu18** [comment]
Sorry that there is no plan to update the code. You can try to do this if you are interested.
