### ISSUE TITLE
How to generate mean_ std.npy?

### ISSUE THREAD

**Issue by jieruyao49** [huiqu18/WeaklySegPartialPoints#2]
When I run the script run.sh  for detection and segmentation, the code reports an error: no such file or directory: '/ data / Mo / mean_ std.npy '. How to generate mean_ std.npy?

**Comment by huiqu18** [comment]
@jieruyao49 If you put the data in the correct folder, the mean_std.npy file can be generated when running  `prepare_data.py`

**Comment by jieruyao49** [comment]
> @jieruyao49 If you put the data in the correct folder, the mean_std.npy file can be generated when running `prepare_data.py`

thanks!
