### ISSUE TITLE
miss   labels_point dirctory

### ISSUE THREAD

**Issue by lzxTopC** [huiqu18/WeaklySegPartialPoints#3]
miss   labels_point dirctory

**Comment by lzxTopC** [comment]
How to deal with miss miss   labels_point dirctory

**Comment by huiqu18** [comment]
@lzxTopC We obtained the points annotation by computing the central point of each nuclear mask.

**Comment by kaiXuewen** [comment]
It's my great pleasure to ask this question .When run Python setup.py install ,we encountered  LINK : fatal error LNK1181: unable to open the input file“\DenseCRFLoss.obj”.

**Comment by huiqu18** [comment]
@kaiXuewen Did you use the same environment setup, i.e., Ubuntu 16.04, Pytorch 1.0.0, Gcc >= 4.9? 
The code was developed a long time ago thus may not support the latest version of libs.

**Comment by kaiXuewen** [comment]
> e

Thank you for your reply！ I try hard to learn from you.
